apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tictactoe
type: Opaque
data:
  mysql-user: bWFkeQ==
  mysql-password: R2FtZUAxMjM=
  mysql-host: MzQuOS44NS42Nw==
  mysql-database: Z2FtZS1tdWx0aXBsYXllci1kYg==