apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tictactoe
type: Opaque
stringData:
  mysql-user: "mady"
  mysql-password: "MadyPass123!"
  mysql-host: "34.9.85.67"
  mysql-database: "ttt_stats"
  DATABASE_URL: "mysql+pymysql://mady:MadyPass123!@34.9.85.67:3306/ttt_stats"