apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tictactoe
type: Opaque
stringData:
  mysql-user: "mady"
  mysql-password: "Game@123"
  mysql-host: "34.9.85.67"
  mysql-database: "game-multiplayer-db"
  DATABASE_URL: "mysql+pymysql://mady:Game%40123@34.9.85.67:3306/game-multiplayer-db"